version: '3'

services:
  database:
    image: 'mysql:5.7.25'
    environment:
      - TZ='+00:00'
      - MYSQL_ROOT_PASSWORD=kudos
      - MYSQL_USER=kudos
      - MYSQL_DATABASE=kudos
      - MYSQL_PASSWORD=kudos
    ports:
      - "3306:3306"

  dev:
    build:
      dockerfile: Dockerfile.dev
      context: .
    volumes:
      - '/app/node_modules'
      - .:/app
      - /tmp:/tmp
    environment:
      - NODE_ENV=development
      - MYSQL_USER=kudos
      - MYSQL_DATABASE=kudos
      - MYSQL_PASSWORD=kudos
      - DB_HOST=database
    ports:
      - "5000:5000"
    depends_on:
      - database
    command: sh -c 'bin/wait-for.sh database:3306 -- yarn db && yarn dev'

  test:
      build:
        dockerfile: Dockerfile.dev
        context: .
      volumes:
        - '/app/node_modules'
        - .:/app
      environment:
        - NODE_ENV=test
        - MYSQL_USER=kudos
        - MYSQL_DATABASE=kudos
        - MYSQL_PASSWORD=kudos
        - DB_HOST=database
      ports:
        - "5000:5000"
      depends_on:
        - database
      command: sh -c 'bin/wait-for.sh database:3306 -- yarn db && yarn test'
