FROM node:lts-alpine AS build

# Set the working directory
WORKDIR /app

# Copy project specification and dependencies lock files
COPY package.json yarn.lock ./

RUN yarn

# Deploy build
FROM node:lts-alpine
WORKDIR /app

# Copy app sources
COPY --from=build /app /app
COPY . .
RUN npx rimraf ./dist/

# Expose application port
EXPOSE 5000

CMD ["yarn", "dev"]